runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /elm.js
  static_files: elm.js
  upload: elm.js
  secure: always

- url: /noop
  script: _go_app
  secure: always
